## server_url = "ws://detect-be.insolvent.app:443"
## credentials = "adsfsdfsdfsdfsdfsdfsdf, 2C5SJCSKSEHK62WV9ENWK6D3K"

[20010]
name = "UserListEvents"
params.limit = 100
params.offset = 0
params.kind = 2

[20020]
name = "UserListSignals"
params.limit = 100
params.offset = 0